#Tien Len TeaM Server
sv.port=19129
limit.ccu=20000
sv.adminpanel=0
db.host=localhost:3306
db.name=kpah
db.user=root
db.password=root
db.maxco=100
db.nameNap=kpah
db.userNap=root
db.pass=root
db.maxNap=30
#
db.host1=localhost:3306
db.name1=kpah
db.user1=root
db.password1=root
db.maxco1=1
#
sv.portnap=19153
sv.server=1
sv.LG=3
sv.range=0
sv.pathLog=D:\\server\\nqsh\\log\\
sv.createRace=2
sv.tablerace=tob_race_257
sv.dayrace=2013-07-11
db.hour=-1
db.run=D:\\nqsh30\\toolRestart.bat
db.minute=2
sv.lang=0
sv.me=0
sv.ph=chienthan
sv.choi=snduca
sv.iplogin=160.250.246.84
sv.portlogin=8023
api.sv=1
api.url=https://domain.com
// 1 la bat 2 la tat
sv.expvantieu=10
sv.Luckyexp=10
sv.ExpQua=10
sv.CodeTest=0
sv.EnableAvtiveCheck=0
sv.isSuKien83=1
sv.isSuKienTrungThul2016=1
sv.isSuKienTet2017=1
sv.isSuKienGioTo2016=1
sv.isSuKienNoel2023=1
sv.isSuKienTetduonglich2024=1
